<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>5b31c608-38c2-4a17-8289-2602d4853b92</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Scootly.Application\Scootly.Application.csproj" />
		<ProjectReference Include="..\Scootly.Infrastructure\Scootly.Infrastructure.csproj" />
	</ItemGroup>

</Project>